// bEBwhcQE1V
// JZmRIEFbqd
// E6m3KGcRfs
// Ny021O5XCT
// kNtCSIPYxF
// dRym3kEfAW
// 1uwJHpMhMI
// L7PsgoKBEc
// 58PwZwPuK0
// OpA0tX4wuj
// UhWfLeP3CE
// eGS6x1yt1U
// gHVDhAVEf6
// jSoAlZQT48
// dC1VT7OGou
// CYxF7gqKjy
// N1nr4Wpixt
// nz9tt60dOw
// ENx7vr8Qbh
// o3TS3qKt0O
// LbwftNT5X0
// l5UiqnvJ4V
// eAwH1Gn9vS
// gVMsONxrSs
// HwvVjJiiWo
// IvIBWicBj8
// 9dCUPW0Xjd
// arP4OlQ8QC
export const storageIndex = {
    searchResults: `searchResults____bEBwhcQE1V`,
    userData: `userData____arP4OlQ8QC`,
};
